### ISSUE TITLE
Show tags in the results panel

### ISSUE THREAD

**Issue by mvadu** [NatelEnergy/grafana-influx-admin#10]
Hi, when you use "group by" clause, Influx returns `tags` array. I don't see them displayed in the results panel. I do see multiple tables for each of the series with series name displayed, but not tags. Is there is a way to show them?

**Comment by ryantxu** [comment]
I just added that on the dev build... will be in the next release

![image](https://user-images.githubusercontent.com/705951/31691478-8c6f2538-b396-11e7-9636-0af7fd151a2b.png)

**Comment by mvadu** [comment]
Thank you for very fast turnaround. Any ETA for the next release date?
