### ISSUE TITLE
Cannot read property 'database' of undefined

### ISSUE THREAD

**Issue by Samuel1989** [NatelEnergy/grafana-influx-admin#11]
Hey all,

I am trying to use this grafana plugin but I am running into the following error when trying to write data:
Cannot read property 'database' of undefined

The database is defined and I am able to query it, but for some reason I am unable to write.

Any help with this would be really appreciated.

Thank you,
Sam

**Comment by ryantxu** [comment]
Looks like this was a bug.  fixed in: 
https://github.com/NatelEnergy/grafana-influx-admin/commit/f93316df06f6d665603d591d697abded799a485f#diff-f968fd283a83e7ce43a5699bcdeed04dL122
