### ISSUE TITLE
Cannot read property 'raw' of undefined in Grafana 5.4

### ISSUE THREAD

**Issue by auntieyi** [NatelEnergy/grafana-influx-admin#14]
After upgrade the grafana to v5.4,
there is an error "Cannot read property 'raw' of undefined".

**Comment by ryantxu** [comment]
Can you try with 5.4.1?  There was a fix added that will likely fix this:
https://github.com/grafana/grafana/issues/14287
https://github.com/NatelEnergy/grafana-discrete-panel/issues/78

**Comment by auntieyi** [comment]
Hi, updated to 5.4.2 and recreated the panel solved the problem.
Thanks.

**Comment by dudusakharovich** [comment]
@auntieyi  - Hey, I also have this problem, how did you fix it ?
What do you mean by recreated the panel ? which panel ?

I'm already working with latest Grafana version 5.4.2

**Comment by auntieyi** [comment]
I created a new "Influx Admin" panel.
It will show error: "Configure an influx database: -- Grafana -- / undefined".
After I select the correct in InfluxDB, it working well.
![image](https://user-images.githubusercontent.com/1725966/50556502-c6f59100-0d14-11e9-94e7-0402464f7430.png)
