### ISSUE TITLE
allow InfluDB selection to use Template variable 

### ISSUE THREAD

**Issue by roscoe57** [NatelEnergy/grafana-influx-admin#5]
this plugin is really cool

but if you have several different Influx databases you need to enter edit mode to select wot one u are interested in.

I have a template variable, which automatically lists the influx databases, it would be nice to be able to use the template variable $datasource in the >Options/InfluxDB 

If you can already do this another better way even better

**Comment by ryantxu** [comment]
added template variable support in master... it will be in the next release (hopefully this week)

![image](https://user-images.githubusercontent.com/705951/31693021-b78337f4-b39c-11e7-96b5-159ff36c6d72.png)

**Comment by mvadu** [comment]
Is there a way to use the `$timeFilter` variable as well?
