### ISSUE TITLE
Option to specify timestamp format / precision

### ISSUE THREAD

**Issue by birengoodco** [NatelEnergy/grafana-influx-admin#6]
Would it be possible to have timestamps automatically display in rfc 3389 format? Or provide an option to specify the format/precision?

**Comment by ryantxu** [comment]
I just added this option to the master branch... it will be released with 0.0.3

**Comment by birengoodco** [comment]
Thanks for including this fix in the next release!! Any estimation of when 0.0.3 will be released? Thanks!

**Comment by ryantxu** [comment]
I could push it at any point... but it assumes the patch:
https://github.com/grafana/grafana/pull/8096
has been applied.  My plan is to wait until it is at least merged in the master branch and then release this
